server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.25.133

leyou:
  sms:
    accessKeyId: LTAI6L8wYEaLjTD4
    accessKeySecret: YImSiADd1zrKggH7buCczGkClYdgN2
    signName: 万方短信验证
    verifyCodeTemplate: SMS_175121785
